spring.application.name=spaceship-station
server.port=8084

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/station_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=station_admin
spring.datasource.password=supersecretpassword

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
