name: my-first-actions
run-name: action-file-one

on:
  push:

jobs:
  job-one:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the branch from repository
        uses: actions/checkout@v4

      - name: Show machine details
        run: |
            hostnamectl

      - name: where am I ?.
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          
      - name: Run unit test
        run: |
          mvn clean test

      - name: List Target folder before jar creation 
        run: |
          ls -lh target

      - name: Build Jar
        run: |
          mvn clean package

      - name: List Target folder after jar creation 
        run: |
          ls -lh target
          
      - name: Display Jar File  
        run: |
          find target -name "*.jar"
          
